import requests
import time
import os
from os import getcwd

print('Made by Nickwasused')
print('*******************')
print('Source for Proxy Servers:')
print('https://raw.githubusercontent.com/clarketm/proxy-list/master/proxy-list.txt')

os.remove("proxylist.txt")
url = "https://raw.githubusercontent.com/clarketm/proxy-list/master/proxy-list.txt"
directory = getcwd()
filename = directory + 'proxylist.txt'
r = requests.get(url)

with open('proxylist.txt', 'a') as the_file:
    the_file.write('***********************************************')
    
with open('proxylist.txt', 'a') as the_file:
    the_file.write('Proxy List generated by Nickwasuseds Proxy Tool')
    
with open('proxylist.txt', 'a') as the_file:
    the_file.write('***********************************************')
    
with open('proxylist.txt', 'a') as the_file:
    the_file.write(r.text)
    
with open('proxylist.txt', 'a') as the_file:
    the_file.write('Source:https://raw.githubusercontent.com/clarketm/proxy-list/master/proxy-list.txt')
    
time.sleep(30)
