import requests #importing
import time
import os
import urllib
import sys
import socket
import ctypes
import urllib.request
import colorama
from colorama import init
from colorama import Fore, Back, Style
from os import getcwd #done
   


init() #init colorrama

ctypes.windll.kernel32.SetConsoleTitleW("Nickwasused´s Proxy Tool") #setting the Window Title

print(Fore.RED + 'Made by Nickwasused') #printing some stuff
print(Fore.RED + '************************')
print(Fore.GREEN + 'Version: 0.8')
print(Fore.WHITE + 'Sources for Proxy Servers:')
print(Back.BLUE + 'https://raw.githubusercontent.com/clarketm/proxy-list/master/proxy-list.txt')
print(Back.BLUE + 'https://raw.githubusercontent.com/a2u/free-proxy-list/master/free-proxy-list.txt')
print(Back.BLUE + 'https://raw.githubusercontent.com/opsxcq/proxy-list/master/list.txt')
print(Back.BLUE + 'https://raw.githubusercontent.com/DarrenRainey/HTTP-Proxy-List/master/lists/1025674') #end printing

os.system('fsutil file createnew proxylist.txt 1') #creating the File "procylist.txt"
os.remove("proxylist.txt") #removing the File "proxylist.txt" to remove duplicats 

url1 = "https://raw.githubusercontent.com/clarketm/proxy-list/master/proxy-list.txt" #url 1-4
url2 = "https://raw.githubusercontent.com/a2u/free-proxy-list/master/free-proxy-list.txt"
url3 = "https://raw.githubusercontent.com/opsxcq/proxy-list/master/list.txt"
url4 = "https://raw.githubusercontent.com/DarrenRainey/HTTP-Proxy-List/master/lists/1025674"

directory = getcwd() #getting the Directory
filename = directory + 'proxylist.txt' #Filename

r = requests.get(url1) #request(download) 1-4
t = requests.get(url2)
l = requests.get(url3)
s = requests.get(url4)

with open('proxylist.txt', 'a') as the_file: #fileopen
    the_file.write('***********************************************')#filewrite
with open('proxylist.txt', 'a') as the_file:
    the_file.write('Proxy List generated by Nickwasuseds Proxy Tool')
with open('proxylist.txt', 'a') as the_file:
    the_file.write('***********************************************')
with open('proxylist.txt', 'a') as the_file:
    the_file.write(r.text) #write the Content of Download 1
with open('proxylist.txt', 'a') as the_file:
    the_file.write(t.text) #write the Content of Download 2
with open('proxylist.txt', 'a') as the_file:
    the_file.write(l.text) #write the Content of Download 3 
with open('proxylist.txt', 'a') as the_file:
    the_file.write(s.text) #write the Content of Download 4

print(Back.YELLOW + '') #printig some Stuff again

num_lines = sum(1 for line in open('proxylist.txt')) #reading the File Lines

print('Got {} Proxyies!'.format(num_lines)) #and Again....
print(Fore.WHITE + "Sleeping 5 Secconds")

time.sleep(5) #waiting
exit() #exiting the Programm
